name: devmobil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.5
  google_generative_ai: ^0.4.6
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  video_player: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/phone.jpg
